### ISSUE TITLE
Difficulty integrating into Docker images

### ISSUE THREAD

**Issue by kovacshuni** [Financial-Times/service-status-go#5]
`go install -a -ldflags="${flags}"` doesn't work with base image _alpine:3.3_

Error:

```
# runtime/cgo
exec: "gcc": executable file not found in $PATH
```

After searching on the webz, glibc is not on alpine, they use musl-libc, so i tried _frolvlad/alpine-glibc_. Same issue regardless. Added `apk --update add gcc`. Other error:

```
# runtime/cgo
/usr/lib/go/src/runtime/cgo/cgo.go:52:19: fatal error: errno.h: No such file or directory
```

Then came to [this](http://stackoverflow.com/questions/19192293/go-build-doesnt-find-my-c-standard-library-when-compiling-cgo-package) discussion: _The go -ldflags parameter passes parameters to the go linkers (5l, 6l, 8l, ...). ... I'm afraid that this parameter won't help you here._

I gave up, it's not worth it.

**Comment by ghost** [comment]
@izzyblues any thoughts based on what you tried around this? @sjwells I know semantic folks are also interested here.

**Comment by ghost** [comment]
Closed due to staleness.
